services:
    ollama:
        container_name: ollama
        image: ollama/ollama:latest
        volumes:
            - ollama_models:/root/.ollama
        ports:
            - 11434:11434
        restart: unless-stopped

volumes:
    ollama_models:
        name: ollama_models
